version: "3.3"
services:
  db:
    build:
      context: .
      args:
        - PGVERSION=${PGVERSION:-17}
        - PARTMAN_VERSION=${PARTMAN_VERSION:-5}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD:-postgres}
